$(function(){
  $('.one').click(function(){
    $('.fa-home').addClass('fa-spin');
  });
  $('.two').click(function(){
    $('.fa-laptop').addClass('fa-spin');
  });
  $('.three').click(function(){
    $('.fa-shopping-cart').addClass('fa-spin');
  });
  $('.four').click(function(){
    $('.fa-book-reader').addClass('fa-spin');
  });
  $('.five').click(function(){
    $('.fa-coffee').addClass('fa-spin');
  });
  $('.six').click(function(){
    $('.fa-hiking').addClass('fa-spin');
  });
  $('.seven').click(function(){
    $('.fa-instagram').addClass('fa-spin');
  });
  $('.eight').click(function(){
    $('.fa-twitter-square').addClass('fa-spin');
  });
  $('.nine').click(function(){
    $('.fa-youtube').addClass('fa-spin');
  });
  $('.ten').click(function(){
    $('.fa-newspaper').addClass('fa-spin');
  });
  $('.eleven').click(function(){
    $('.fa-exclamation-triangle').addClass('fa-spin');
  });
  $('.twelve').click(function(){
    $('.fa-envelop').addClass('fa-spin');
  });
});
